version: "3.8"
services:
  backend:
    build: ./chat-backend
    container_name: chat-backend
    ports:
      - "5000:5000"

  frontend:
    build: ./chat-frontend
    container_name: chat-frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes: {}
